import { Course, AISuggestion } from '../types/course';

export const mockCourses: Course[] = [
  {
    id: '1',
    title: 'Mathématiques Avancées',
    professor: 'Dr. Martin',
    location: 'Salle A101',
    startTime: '09:00',
    endTime: '11:00',
    dayOfWeek: 1,
    color: '#3b82f6',
    description: 'Algèbre linéaire et calcul différentiel',
    credits: 4,
  },
  {
    id: '2',
    title: 'Programmation Web',
    professor: 'Prof. Dubois',
    location: 'Lab Info B202',
    startTime: '14:00',
    endTime: '16:00',
    dayOfWeek: 1,
    color: '#10b981',
    description: 'HTML, CSS, JavaScript et React',
    credits: 3,
  },
  {
    id: '3',
    title: 'Physique Quantique',
    professor: 'Dr. Lambert',
    location: 'Amphi C',
    startTime: '10:00',
    endTime: '12:00',
    dayOfWeek: 2,
    color: '#8b5cf6',
    description: 'Introduction à la mécanique quantique',
    credits: 4,
  },
  {
    id: '4',
    title: 'Histoire de l\'Art',
    professor: 'Prof. Rousseau',
    location: 'Salle D301',
    startTime: '13:00',
    endTime: '15:00',
    dayOfWeek: 3,
    color: '#f59e0b',
    description: 'Renaissance et période moderne',
    credits: 2,
  },
  {
    id: '5',
    title: 'Base de Données',
    professor: 'Dr. Chen',
    location: 'Lab Info B203',
    startTime: '09:00',
    endTime: '11:00',
    dayOfWeek: 4,
    color: '#ef4444',
    description: 'SQL, NoSQL et modélisation',
    credits: 3,
  },
];

export const mockSuggestions: AISuggestion[] = [
  {
    id: 's1',
    type: 'optimization',
    message: 'Vous avez 3 heures libres le mardi après-midi, idéal pour réviser Mathématiques Avancées',
    priority: 'medium',
  },
  {
    id: 's2',
    type: 'recommendation',
    message: 'Considérez espacer vos cours de programmation pour mieux assimiler les concepts',
    courses: ['2', '5'],
    priority: 'low',
  },
  {
    id: 's3',
    type: 'optimization',
    message: 'Votre charge est bien répartie avec 16 crédits sur 4 jours',
    priority: 'low',
  },
];
